### ISSUE TITLE
DYDXAdapter is returning the borrow rate instead of the supply rate

### ISSUE THREAD

**Issue by fvictorio** [primeradiant/MetaMoneyMarket#45]
The `DYDXAdapter` contract is using the `getMarketInterestRate` method of `SoloMargin`, but that returns the borrow rate, not the supply rate.

The supply rate is computed by multiplying 0.9 * X * B, where X is the utilization of the market and B is the borrow rate.

The utilization of the market is the amount borrowed vs the amount lent. Quoting one of the admins in the Telegram channel for future reference:

> For the utilization, use the token (aka WEI) amount rather than the evm storage (aka PAR) amount. You can get the wei amount from the par amount by multiplying the par by the index of the market. There are two indices, one for the supply and one for the borrow side. So
market.supplyWei = market.totalPar.supply * index.supply
market.borrowWei = market.totalPar.borrow * index.borrow
getMarketTotalPar() should get you the market.totalPar values and getMarketIndex() should get you the index values

See also: https://help.dydx.exchange/en/articles/2924246-how-do-interest-rates-work

**Comment by fvictorio** [comment]
This seems to give the correct result:

```
totalPar = solo.getMarketTotalPar(marketId)
index = solo.getMarketCurrentIndex(marketId)
utilization = (totalPar.borrow * index.borrow) / (totalPar.supply * index.supply)
borrowRate = solo.getMarketInterestRate(marketId)
supplyRate = 0.9 * utilization * borrowRate
```

**Comment by kingjacob** [comment]
USDC seems to be displaying the correct dydx supply rate. I also deposited a usdc into MMM at the same time this rate was displayed and it was sent to dydx.
<img width="706" alt="Screen Shot 2019-07-26 at 4 04 28 PM" src="https://user-images.githubusercontent.com/806312/61985766-88306c80-afbf-11e9-9b0f-ccc4a8b6ae72.png">
<img width="395" alt="Screen Shot 2019-07-26 at 4 04 37 PM" src="https://user-images.githubusercontent.com/806312/61985767-88306c80-afbf-11e9-9380-438cbe96009d.png">

**Comment by fvictorio** [comment]
This seems to be fixed now, but we won't be sure until the dydx rate for DAI or USDC is bigger than the corresponding rate in Compound. When that happens, if the table shows the correct rate, then it will suggest it's working fine.

**Comment by kingjacob** [comment]
@fvictorio this seems finished, did anything pop up in the logging you had done?
