### ISSUE TITLE
Basic Kyber Swap Integration

### ISSUE THREAD

**Issue by kingjacob** [primeradiant/MetaMoneyMarket#64]
Two UI's 
1)"Get Tokens" button above the table on the right side, in the same row as My Account which is always there. 

2)if wallet balance is 0 the Deposit buttons says "Get Dai" and links to the kyber widget, not the deposit modal.

**Comment by pablofullana** [comment]
hey @kingjacob has this issue been closed by #71? or are we also waiting for #80 to be merged before closing it?
